git:
  paging:
    colorArg: always
    pager: delta --dark
    useConfig: true

gui:
  mouseEvents: true
  theme:
    activeBorderColor:
      - '#f5e0dc'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#f5e0dc'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
  authorColors:
    '*': '#b4befe'
  nerdFontsVersion: '2'

os:
  edit: 'nvim {{filename}}'
  open: 'nvim {{filename}}'

keybinding:
  universal:
    nextBlock-alt2: <disabled>
    prevBlock-alt2: <disabled>
    nextTab: <tab>
    prevTab: <backtab>
    optionMenu: 'x'